name: Update Membership Counts

on:
  schedule:
    # Run on the first of every month
    - cron: 0 0 1 * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v1
    - name: Install dependencies and run script
      run: |
        sudo apt-get update && sudo apt-get install -y python3 python3-pip wget
        sudo pip3 install requests
        # Ensure using a particular version
        wget https://raw.githubusercontent.com/USRSE/usrse.github.io/d54c92c1812deb14d5d80fa27bd0e70526313d99/scripts/update_counts.py
        chmod +x update_counts.py
        mv update_counts.py scripts/update_counts.py
        python3 scripts/update_counts.py
    - name: Checkout New Branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "GitHub Actor: ${GITHUB_ACTOR}"
        git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
        git branch
        git checkout -b update/member-count-$(date '+%Y-%m-%d')
        git branch

        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"

        git add _data/memberCounts.csv
        git commit -m "Automated deployment to update Member Counts $(date '+%Y-%m-%d')" --allow-empty
        git push origin update/member-count-$(date '+%Y-%m-%d')
    - name: Open pull request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_AGAINST: "master"
      run: |
          export BRANCH_FROM="update/member-count-$(date '+%Y-%m-%d')"
          wget https://raw.githubusercontent.com/USRSE/usrse.github.io/303a80b7991c3d4b97fa1f3a15f2dfa1e6aac43c/scripts/pull-request.sh
          chmod +x ./pull-request.sh
          /bin/bash ./pull-request.sh
